defaults:
  - config
  - override train/optimizer: adamw
  - _self_

gpus: [0,1]
name: ${model.model_name}

info:
  project: Neural_Substitution_Deit_ImageNet

train:
  epochs: 300
  batch_size: 256
  num_workers: 8

  scheduler:
    warmup_epochs: 5
    warmup_lr: 1e-6
    min_lr: 1e-5
  
  optimizer:
    grad_accumulation: 2
    lr: 5e-4
    opt_eps: 1e-8
    momentum: 0.9
    weight_decay: 5e-2

model:
  model_name:
  drop_path_rate: 0.1

dataset:
  augmentation:
    mixup: 0.8
    cutmix: 1.0
    crop_pct: 0.9
    auto_aug: rand-m9-mstd0.5-inc1
    train_interpolation: bicubic
    re_prob: 0.25
    smoothing: 0.1
    color_jitter: 0.3