defaults:
  - config
  - override train/optimizer: lamb
  - _self_

gpus: [ 0,1,2,3,4,5,6,7 ]
name: ${model.model_name}

info:
  project: Neural_Substitution_ImageNet

train:
  epochs: 100
  batch_size: 128
  num_workers: 10
  bce_loss: True
  target_thresh: 0.2

  lr_scheduler:
    warmup_epochs: 3
    warmup_lr: 1e-4
    min_lr: 1e-6

  optimizer:
    grad_accumulation: 2
    lr: 3.5e-3
    weight_decay: 1e-2

model:
  model_name:
  drop_path_rate: 0.05 # 0.05
  neural_drop_rate: 0.0

dataset:
  augmentation:
    mixup: 0.1
    cutmix: 1.0
    crop_pct: 0.95
    aa: rand-m7-mstd0.5-inc1
    smoothing: 0.0